(() => {
  const initialWorks = [
    { id: 'archive-expedition', status: 'published', year: '2021', location: { uk: 'Київ / Харків / Львів', en: 'Kyiv / Kharkiv / Lviv' }, title: { uk: 'ARCHIVE: EXPEDITION', en: 'ARCHIVE: EXPEDITION' }, description: { uk: 'Серія сольних, дуетних і групових перформансів, створених у межах мандрівного проєкту.', en: 'A series of solo, duo and group performances created within a travelling project.' }, cover: '../assets/archive-kyiv-01.webp', gallery: '../assets/archive-kyiv-01.webp\n../assets/archive-kyiv-02.webp\n../assets/archive-kyiv-03.webp' },
    { id: 'crossing-2', status: 'published', year: '2021', location: { uk: 'Міжнародний проєкт', en: 'International project' }, title: { uk: 'CROSSING 2.0', en: 'CROSSING 2.0' }, description: { uk: 'Колективний перформативний проєкт про перехід, дистанцію та взаємну присутність.', en: 'A collective performance project about transition, distance and mutual presence.' }, cover: '../assets/crossing-01.webp', gallery: '../assets/crossing-01.webp\n../assets/crossing-02.webp\n../assets/crossing-03.webp' },
    { id: 'exploring-don-quixote', status: 'published', year: '2019', location: { uk: 'Франкфурт-на-Майні', en: 'Frankfurt am Main' }, title: { uk: 'EXPLORING DON QUIXOTE', en: 'EXPLORING DON QUIXOTE' }, description: { uk: 'Тривалий груповий перформанс і лабораторія під керівництвом Юргена Фрітца.', en: 'A durational group performance and laboratory led by Jürgen Fritz.' }, cover: '../assets/don-quixote-01.webp', gallery: '../assets/don-quixote-01.webp\n../assets/don-quixote-02.webp\n../assets/don-quixote-03.webp' },
    { id: 'zabih', status: 'published', year: '2019', location: { uk: 'Львів', en: 'Lviv' }, title: { uk: 'JÜRGEN FRITZ WORKSHOP / ZABIH', en: 'JÜRGEN FRITZ WORKSHOP / ZABIH' }, description: { uk: 'Груповий перформанс, створений під час воркшопу Юргена Фрітца.', en: 'A group performance developed during Jürgen Fritz’s workshop.' }, cover: '../assets/zabih-01.webp', gallery: '../assets/zabih-01.webp\n../assets/zabih-02.webp\n../assets/zabih-03.webp' },
    { id: 'shards-of-normality', status: 'published', year: '2025', location: { uk: 'Кельн / Берлін', en: 'Cologne / Berlin' }, title: { uk: 'SHARDS OF NORMALITY', en: 'SHARDS OF NORMALITY' }, description: { uk: 'Міжнародний ансамблевий проєкт про фрагментарність повсякденності.', en: 'An international ensemble project about the fragmentary nature of everyday life.' }, cover: '../assets/shards-01.webp', gallery: '../assets/shards-01.webp\n../assets/shards-02.webp\n../assets/shards-03.webp' },
    { id: 'performance-platform-lublin', status: 'published', year: '2017', location: { uk: 'Люблін', en: 'Lublin' }, title: { uk: 'BORDER', en: 'BORDER' }, description: { uk: 'Сольна робота, показана на Performance Platform Lublin.', en: 'A solo work presented at Performance Platform Lublin.' }, cover: '../assets/border-01.webp', gallery: '../assets/border-01.webp\n../assets/border-02.webp\n../assets/border-03.webp' }
  ];
  const storageKey = 'ira-admin-drafts-v1';
  const clone = value => JSON.parse(JSON.stringify(value));
  let works = JSON.parse(localStorage.getItem(storageKey) || 'null') || clone(initialWorks);
  let selectedId = works[0]?.id;
  let locale = 'uk';
  const list = document.querySelector('#work-list');
  const editor = document.querySelector('#editor-panel');
  const toast = message => { document.querySelector('#toast').textContent = message; window.clearTimeout(toast.timer); toast.timer = window.setTimeout(() => { document.querySelector('#toast').textContent = ''; }, 2600); };
  const save = () => { localStorage.setItem(storageKey, JSON.stringify(works)); toast('Збережено локально'); renderList(); };
  const selected = () => works.find(work => work.id === selectedId) || works[0];
  const renderList = () => {
    document.querySelector('#work-count').textContent = works.length;
    list.replaceChildren(...works.map(work => {
      const row = document.createElement('article'); row.className = `work-row${work.id === selectedId ? ' is-selected' : ''}`; row.draggable = true; row.dataset.id = work.id;
      row.innerHTML = `<div class="work-thumb"><img src="${work.cover}" alt=""></div><div><h3>${work.title[locale] || work.title.uk}</h3><p>${work.year} / ${work.location[locale] || work.location.uk}</p></div><span class="work-status${work.status === 'draft' ? ' is-draft' : ''}" title="${work.status}"></span>`;
      row.addEventListener('click', () => { selectedId = work.id; renderList(); renderEditor(); });
      row.addEventListener('dragstart', () => { row.classList.add('is-dragging'); });
      row.addEventListener('dragend', () => { row.classList.remove('is-dragging'); });
      row.addEventListener('dragover', event => event.preventDefault());
      row.addEventListener('drop', event => { event.preventDefault(); const from = works.findIndex(item => item.id === selectedId); const to = works.findIndex(item => item.id === row.dataset.id); if (from < 0 || to < 0 || from === to) return; const [moved] = works.splice(from, 1); works.splice(to, 0, moved); save(); });
      return row;
    }));
  };
  const renderEditor = () => {
    const work = selected(); if (!work) { editor.innerHTML = '<p>Додайте першу роботу.</p>'; return; }
    editor.innerHTML = `<div class="editor-head"><div><p class="eyebrow">EDIT WORK</p><h2>${work.title[locale] || 'Нова робота'}</h2></div><select class="status-select" id="status-field"><option value="published" ${work.status === 'published' ? 'selected' : ''}>Опубліковано</option><option value="draft" ${work.status === 'draft' ? 'selected' : ''}>Чернетка</option></select></div><div class="locale-tabs"><button type="button" class="locale-tab${locale === 'uk' ? ' is-active' : ''}" data-locale="uk">UA</button><button type="button" class="locale-tab${locale === 'en' ? ' is-active' : ''}" data-locale="en">EN</button></div><div class="form-grid"><div class="field"><label for="title-field">Назва</label><input id="title-field" data-field="title" value="${work.title[locale] || ''}"></div><div class="field"><label for="year-field">Рік</label><input id="year-field" data-field="year" value="${work.year}"></div><div class="field full"><label for="location-field">Місце / формат</label><input id="location-field" data-field="location" value="${work.location[locale] || ''}"></div><div class="field full"><label for="description-field">Опис</label><textarea id="description-field" data-field="description">${work.description[locale] || ''}</textarea></div><div class="field full"><label for="cover-field">Обкладинка / URL зображення</label><input id="cover-field" data-field="cover" value="${work.cover}"><div class="cover-preview"><img src="${work.cover}" alt="Попередній перегляд"></div></div><div class="field full"><label for="gallery-field">Галерея / по одному URL на рядок</label><textarea id="gallery-field" data-field="gallery" spellcheck="false">${work.gallery}</textarea></div></div><div class="editor-foot"><span class="mono">ID: ${work.id}</span><button type="button" class="text-button danger-button" id="delete-work">Видалити чернетку</button></div>`;
    editor.querySelectorAll('[data-locale]').forEach(button => button.addEventListener('click', () => { locale = button.dataset.locale; renderList(); renderEditor(); }));
    editor.querySelectorAll('[data-field]').forEach(field => field.addEventListener('input', event => { const key = event.target.dataset.field; work[key] = ['title', 'location', 'description'].includes(key) ? { ...work[key], [locale]: event.target.value } : event.target.value; if (key === 'cover') editor.querySelector('.cover-preview img').src = event.target.value; }));
    editor.querySelector('#status-field').addEventListener('change', event => { work.status = event.target.value; renderList(); });
    editor.querySelector('#delete-work').addEventListener('click', () => { if (works.length === 1) return; works = works.filter(item => item.id !== work.id); selectedId = works[0].id; save(); renderEditor(); });
  };
  document.querySelector('#save-button').addEventListener('click', save);
  document.querySelector('#new-work').addEventListener('click', () => { const id = `new-work-${Date.now()}`; works.unshift({ id, status: 'draft', year: new Date().getFullYear().toString(), location: { uk: 'Нове місце', en: 'New location' }, title: { uk: 'НОВА РОБОТА', en: 'NEW WORK' }, description: { uk: '', en: '' }, cover: '../assets/hero-green.webp', gallery: '../assets/hero-green.webp' }); selectedId = id; renderList(); renderEditor(); });
  document.querySelector('#export-button').addEventListener('click', () => { const blob = new Blob([JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), works }, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'ira-portfolio-draft.json'; link.click(); URL.revokeObjectURL(link.href); toast('JSON експортовано'); });
  document.querySelector('#import-input').addEventListener('change', event => { const [file] = event.target.files; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const imported = JSON.parse(reader.result); if (!Array.isArray(imported.works)) throw new Error('Invalid'); works = imported.works; selectedId = works[0]?.id; save(); renderEditor(); toast('JSON імпортовано'); } catch { toast('Не вдалося імпортувати'); } }; reader.readAsText(file); });
  document.querySelector('#reset-button').addEventListener('click', () => { works = clone(initialWorks); selectedId = works[0].id; save(); renderEditor(); });
  document.querySelector('#notice-close').addEventListener('click', event => event.currentTarget.closest('.notice').remove());
  document.querySelectorAll('.side-link').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.side-link').forEach(item => item.classList.toggle('is-active', item === button)); document.querySelectorAll('[data-view-panel]').forEach(panel => { panel.hidden = panel.dataset.viewPanel !== button.dataset.view; }); }));
  renderList(); renderEditor();
})();
